name: TopWeight
options:
  bundleIdPrefix: com.topweight
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    SWIFT_VERSION: "6.0"
targets:
  TopWeight:
    type: application
    platform: iOS
    sources:
      - path: TopWeight
        type: group
        includes:
          - "**/*.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.topweight.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
